# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: mkdir public/assets && mv dist/assets/* public/assets/ && rm public/index.css
      - name: Copy public files to developia-io repository
        uses: dobbelina/multi_file_bandit@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source_file: "public"
          destination_repo: "developia-io/developia-io"
          destination_branch: "master"
          destination_folder: "public" # Omit if destination root
          user_email: "31591904+ecebeci@users.noreply.github.com"
          user_name: "Three-js-BOT"
          commit_message: ${{ github.event.head_commit.message }}
          rsync_option: "-avrh"
